version: "3.9"

services:
  nm-api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "${NM_API_PORT:-5000}:8080"
      - "${NM_GRPC_PORT:-5001}:8444"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      Encryption__SecretKey: "-----BEGIN CERTIFICATE-----
MIIEnDCCAoQCAQAwDQYJKoZIhvcNAQENBQAwEzERMA8GA1UEAwwIR296YXJnYWgw
IBcNMjQwNjA2MTMwNTA0WhgPMjEyNDA1MTMxMzA1MDRaMBMxETAPBgNVBAMMCEdv
emFyZ2FoMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4zChAhKw7Ns/
Y1eBAf/9xGaDH37g+XP3XGR6VymA5QeIgcbFvgjImQKbFCmGV0QvMYiMB7ia5G3X
sjIf8y8TFTQuAD61oIddxqu1YGilwovEZu2Or6KpVUX7tWO9Vv1tI16P4ajuj30B
IGJGhYQ5IGQwWKDZntiP88lPi7rvO4ROW7u3S+8W6sSJpO7WLM1oHrOPi5YijwnK
GQH6pnPBMDc455okaC0foHZLmiXqbZ9kzEqW/aMt3RCMUCcEakSLB13LfkHpIPvR
FuiC5ErMUrbsHbRfRpHq47pCi58Lnh6mBU5dMtM6vftdIP5o4jXPlOQi27F6Q6vP
3zFNV7BvsKlmjISGQa8kwxJnXRkZIxFox6l7buXBWm9D86pJo50ORf6MEHyYuNel
4PKTKsddxpklBZAgOdInGmCJq04wI1Jf1n51EamGOplyTOc6i5qbKnMP+c+L8uty
i7AKDO00NPm6JItO3A398HTJENWd+oJfvJxcol0aU6g2zPZHqveCvytkjVmkGA1Z
aXayNS0b9I4uA5KgKnDryD8mvQU0MjDPf/huimO+8zxi5yD+uT1XOFeoM2KuxE+H
B9CNmvS01XioWajM6x+Na3F227jHyi7M5+xFlIKYcyb2F2zBIqd1hz9JWtnBBc0A
YR8E0OOG6ZqIdax9HVq8vTF+l4Yd3rECAwEAATANBgkqhkiG9w0BAQ0FAAOCAgEA
h2QpMkdh/XtAmE+af2UQELgK/N2UlcMw9Onfn3wrbyt7S03LkzavZR/l3VDZldJE
7NrZ/9O4uX+ahwgsvAeZvmGPSpT1wyTu0iqQoRBO0yMqXzYp/imYX6l3DbDO9q47
iFOWkZy3+N0x8j0+hHat0cRX48NB9WNlSNnWNXrBl+yjcI5KfG8+VE9rDOlRHKZf
vnFvkDcKraeqWrSSDJQW+mheCv0avX1P2udXZkDm8Jl4t5xsXQ4pb7noc6O41slF
CWb2ATyBIuPFIXRwEC0y7BRL7WkmVJH2xZ1+sbE9BFS/UHtyEnY6g4xHMpcpelid
YxVZNTmUbWpei+iSg94ExpqXMqs7y2TsRalz3oFuTsc/OL4/YT2O470rL5+HkiWK
QSM4t/9jMxyF0qbrcNUOpAh1daZ7LbnOGjhZbocrIhuG/e9vODjjjATrFunDlVey
zvb29G8qDW/mPu+cQ6TAh7h0IIDhE1SAYdaedU4IQ0QrbvXbmYhVqLCROsAosPod
fC9zjsWoCa9kP9TmqHcfc6qSfQAis7LQKRu4Gh96+MipSoN4USJiRwkyJDdNZDa/
HELRWJ++4EbNyn4Osvarr5Av2/wF/umcaiRpIHhw2Qogd20GthxxjD27NPQwbanE
40tLu9A8y0M7vqLO0n5eCa2eTq42jJ0E8R7J8UzntDU=
-----END CERTIFICATE-----"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
