services:
  nm-api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ApiSecret__Key: "${API_SECRET}"
     
    volumes:
      - /var/lib/easyhub-instance-data:/var/lib/easyhub-instance-data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
    user: root
