version: "3.9"

services:
  nm-api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
    user: root
